env:
  matrix:
  - SCRIPT="./build-me.sh language1"
  - SCRIPT="./build-me.sh language2"
  - SCRIPT="./build-me.sh language3"
  - SCRIPT="./build-me.sh language4"
before_script:
- echo "before_script $SCRIPT"
- . ./travis/travis-functions.sh
- log_env_variables
- load_version_from_file
script:
- . ./travis/travis-functions.sh
- echo "Script operation $OPERATION"
- bash -c "$SCRIPT $OPERATION"
jobs:
  include:
    - stage: publish
      script: /bin/bash ./travis/publish.sh
      if: branch = env(DEV_BRANCH) AND type != pull_request
      env:
        - SCRIPT="./build-me.sh language1"
    - stage: release
      script: /bin/bash ./travis/release.sh
      if: branch = env(RELEASE_BRANCH) type != pull_request AND env(TRAVIS_COMMIT_MESSAGE) = release
      env:
        - SCRIPT="./build-me.sh language1"
    - stage: post release
      script: /bin/bash travis/travis-functions.sh post_release_version_file
      if: branch = env(RELEASE_BRANCH) type != pull_request AND env(TRAVIS_COMMIT_MESSAGE) = release
      env:
        - SCRIPT="./build-me.sh language1"
