env:
  matrix:
  - SCRIPT="./build-me.sh language1"
  - SCRIPT="./build-me.sh language2"
  - SCRIPT="./build-me.sh language3"
  - SCRIPT="./build-me.sh language4"
before_script:
- echo "BEFORE SCRIPT $SCRIPT"
script:
- bash $SCRIPT "Another"
jobs:
  include:
    - stage: release
      env:
        - SCRIPT="./build-me.sh language1"
      script: /bin/sh release-me.sh
      if: branch = $RELEASE_BRANCH AND type != pull_request AND $TRAVIS_COMMIT_MESSAGE = "release"
    - stage: post release
      env:
        - SCRIPT="./build-me.sh language1"
      script: /bin/sh travis/post-release.sh
      if: branch = $RELEASE_BRANCH AND type != pull_request AND $TRAVIS_COMMIT_MESSAGE = "release"
