env:
  matrix:
  - SCRIPT="./build-me.sh language1"
  - SCRIPT="./build-me.sh language2"
  - SCRIPT="./build-me.sh language3"
  - SCRIPT="./build-me.sh language4"
before_script:
- echo "BEFORE SCRIPT $SCRIPT"
- . ./travis/travis-functions.sh
- resolve_operation
script:
- echo "Script operation $OPERATION"
jobs:
  include:
    - stage: publish
      env:
        - SCRIPT="./build-me.sh language1"
      script: /bin/bash publish-me.sh
      if: $OPERATION = "publish"
    - stage: release
      env:
        - SCRIPT="./build-me.sh language1"
      script: /bin/bash release-me.sh
      if: $OPERATION = "release"
    - stage: post release
      env:
        - SCRIPT="./build-me.sh language1"
      script: /bin/bash travis/travis-functions.sh post_release
      if: $OPERATION = "release"
